### ISSUE TITLE
Crashes after selecting website

### ISSUE THREAD

**Issue by mueller-ma** [HugoGresse/Anecdote#19]
When I start the app, select a website and click on save, the app crashes. This happens with all website I have tested

F-Droid version on Android 6.0.1

**Comment by HugoGresse** [comment]
Hi, I've release version 1.1.2 today on Google Play store, F-Droid should build it tonight. I'll update this once F-Droid version is up to date. Sorry for the inconvenience.

**Comment by mueller-ma** [comment]
I will test it and give feedback ASAP

**Comment by mueller-ma** [comment]
Working now with Play Store Version
F-Droid didn't built until now

**Comment by HugoGresse** [comment]
you're right, I'll check what's going on with the F-Droid update next week. I'll also mprove the app on the issue contributor pointed out and merge your PR. It will be great if you can squash all your commit on https://github.com/HugoGresse/Anecdote/pull/24

**Comment by mueller-ma** [comment]
Sry, I have no idea how to squash commits
