### ISSUE TITLE
The save button overlpase the text in the site chooser view

### ISSUE THREAD

**Issue by ghost** [HugoGresse/Anecdote#22]
My phone screen is 4.5 inches

![screenshot_2016-12-07-13-18-14](https://cloud.githubusercontent.com/assets/7694864/20967448/d7face1c-bc7f-11e6-9aab-fa99d59bc64a.png)

**Comment by HugoGresse** [comment]
Will fix it for next release

**Comment by HugoGresse** [comment]
solved in https://github.com/HugoGresse/Anecdote/pull/28
