### ISSUE TITLE
Remove some "translatable=false"

### ISSUE THREAD

**Issue by mueller-ma** [HugoGresse/Anecdote#23]
Can you remove some "translatable=false" in strings.xml, e.g. from error_server_unknown or about_libraries (so I can translate the "by")

**Comment by HugoGresse** [comment]
will do

**Comment by HugoGresse** [comment]
done, see https://github.com/HugoGresse/Anecdote/commit/9dce89cdf912aa7a470a28e73d246a07f80fe137
