### ISSUE TITLE
Add Google Play desc in strings

### ISSUE THREAD

**Issue by mueller-ma** [HugoGresse/Anecdote#25]
There are two typos in the About Site "The application contents does not belog to Anecdte."

Can you include this string in strings.xml?

**Comment by mueller-ma** [comment]
@HugoGresse there is another string that is not in strings.xml: When creating a website with wrong cronfig I get "Website configuration is wrong:" and a button "retry"

**Comment by HugoGresse** [comment]
will do

**Comment by HugoGresse** [comment]
PR open https://github.com/HugoGresse/Anecdote/pull/37

**Comment by HugoGresse** [comment]
If you can translate in hindi too it's marvelous :D

**Comment by mueller-ma** [comment]
@HugoGresse I miss the "retry"-button string

**Comment by HugoGresse** [comment]
my bad, done now

**Comment by mueller-ma** [comment]
@HugoGresse edit your messeage and remove the token!

**Comment by HugoGresse** [comment]
hmm thanks

**Comment by HugoGresse** [comment]
merged

**Comment by mueller-ma** [comment]
SimpleMobileTools included the Google Play Description in strings.xml: https://github.com/SimpleMobileTools/Simple-Notes/blob/master/app/src/main/res/values/strings.xml

Can you do that, too?

**Comment by HugoGresse** [comment]
sure, probably for next release.

**Comment by HugoGresse** [comment]
@ashed @mueller-ma can you complete them for DE and RU? I've just added it, see https://github.com/HugoGresse/Anecdote/commit/e54fe28d519668afe342e00bf27e7e81edfead3e
