### ISSUE TITLE
Add XKCD

### ISSUE THREAD

**Issue by mueller-ma** [HugoGresse/Anecdote#26]
Add xkcd as a default page

**Comment by HugoGresse** [comment]
WIP

**Comment by HugoGresse** [comment]
I need to update the app to be able to load more item when the website only has one page for each item. But you can already use the app to display the first item of xkcd :D

**Comment by HugoGresse** [comment]
should be done within 3 days

**Comment by HugoGresse** [comment]
release planned tomorrow same time, with the restore_change and string translation opti

**Comment by mueller-ma** [comment]
can you give me some time to translate new strings before releasing a new version?

**Comment by HugoGresse** [comment]
done. v1.1.4 is live on Google Play Store. XKCD works great
