### ISSUE TITLE
Move restore_websites to settings menu

### ISSUE THREAD

**Issue by mueller-ma** [HugoGresse/Anecdote#32]
Would be a better place, because its a complete reset and can be tabed accidentially

**Comment by HugoGresse** [comment]
will do, should be moved within a new advanced settings

**Comment by HugoGresse** [comment]
Can you translate "Remove all websites from the app. May be useful if some websites are not working." to german? it the summary of the restore button.

**Comment by mueller-ma** [comment]
"Alle Webseiten aus der App entfernen. Hilfreich, wenn einige Webseiten nicht funktionieren"

**Comment by HugoGresse** [comment]
thanks, releasing version within some hours, see https://github.com/HugoGresse/Anecdote/pull/40

**Comment by mueller-ma** [comment]
There is still the old name in Google Play

**Comment by HugoGresse** [comment]
thanks, gona change it for next release
