### ISSUE TITLE
[Feature Request] Download button

### ISSUE THREAD

**Issue by Sirove** [HugoGresse/Anecdote#49]
It would be nice having a possibility to download pictures and GIFs to show them offline to friends. Maybe even to download posts (text only) as pictures.

**Comment by HugoGresse** [comment]
Like an Favorite option? I will add the option to save the images in the phone and later on I'm gona add a favorite system that should do it.

**Comment by HugoGresse** [comment]
Image download has been done (not in production), working on the favorite option now!

**Comment by HugoGresse** [comment]
Download button is not live on long press on the image (only image :/). Favoris is also in the beta 1.2.0 on the store, you can register for the beta here: https://play.google.com/apps/testing/io.gresse.hugo.anecdote
