### ISSUE TITLE
Russian translation of strings.xml

### ISSUE THREAD

**Issue by ashed** [HugoGresse/Anecdote#52]
[strings_ru.zip](https://github.com/HugoGresse/Anecdote/files/902699/strings_ru.zip)
clipboard content pasting breack formatting in my case.

**Comment by HugoGresse** [comment]
Thanks for this, can you make it a little more readable, like adding correct line break corresponding to the base text? thanks!

**Comment by HugoGresse** [comment]
done, in version 1.1.5
