### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by ashed** [HugoGresse/Anecdote#53]
<resources>
	<string name="using" modified="true">Сторонние библиотеки</string>
	<string name="error_nointernet" modified="true">Нет соединения с интернетом</string>
	<string name="dialog_website_add" modified="true">Добавить</string>
	<string name="error_parsing" modified="true">Нельзя разобрать %s вебсайт</string>
	<string name="open_intent_browser_error" modified="true">Не открываются детали, проверьте конфиг. адреса</string>
	<string name="action_restore" modified="true">Восстановить вебсайты</string>
	<string name="error_responsefail" modified="true">Не загружается вебсайт, ошибка %s</string>
	<string name="action_copy" modified="true">Копировать</string>
	<string name="app_long_description" modified="true">Особенности: 9GAG фид (изображения и видео) с 9GAG Hot, Trending and Fresh             - xkcd             - фиды цитат с fmylife.com (FML), Bash.org, viedemerde.fr (VDM), danstonchat.com (DTC) и более             - простой и эффективный интерфейс          - бесконечный скролл и протяжка для обновления\n- нет странных разрешений, нет фоновых заданий\n- добавление своего веб-сайта нужно немного знать html  \n Anecdote - это простое и мощное приложение для чтения сайтов цитат. Очень легкое, быстрое и простое. \nС открытым исходным кодом на GitHub: https://github.com/HugoGresse/Anecdote          Контент, отображаемый в приложении не принадлежит Anecdote.</string>
	<string name="error_loadfail" modified="true">Нельзя загрузить %s</string>
	<string name="pref_cat_advanced" modified="true">Расширенные настройки</string>
	<string name="dialog_website_firstpagezero_hint" modified="true">Если номер первой страницы - 0</string>
	<string name="error_wrongconfig" modified="true">Конфигурация вебсайта неверна</string>
	<string name="dialog_website_save" modified="true">Сохранить</string>
	<string name="dialog_website_url_hint" modified="true">Адрес вебсайта</string>
	<string name="action_open" modified="true">Открыть</string>
	<string name="dialog_website_selector_hint" modified="true">DOM selector</string>
	<string name="action_website" modified="true">Действие</string>
	<string name="pref_rowstriping_summary" modified="true">Доб-ть фон для разделения цитат</string>
	<string name="copied" modified="true">Скопировано в буфер</string>
	<string name="dialog_website_edit_title" modified="true">Правка</string>
	<string name="error_server" modified="true">Ошибка сервера</string>
	<string name="dialog_website_error_pagename" modified="true">Добавить имя страницы</string>
	<string name="action_website_add_custom" modified="true">Добавить настраив. вебсайт</string>
	<string name="app_share_credits" modified="true">- через Anecdote http://bit.ly/anecdoteapp</string>
	<string name="dialog_website_error_url" modified="true">Отсутствует адрес вебсайта</string>
	<string name="dialog_websitechooser_title" modified="true">Выберите любимые сайты</string>
	<string-array name="anecdote_content_dialog"><item index="0">Копирование ссылки</item></string-array>
	<string name="dialog_website_name_hint" modified="true">Имя вебсайта</string>
	<string name="navigation_drawer_open" modified="true">Открыть navigation drawer</string>
	<string name="action_edit" modified="true">Правка</string>
	<string name="action_website_noteditable_toast" modified="true">Нельзя править отдаленный вебсайт</string>
	<string name="navigation_drawer_close" modified="true">Закрыть navigation drawer</string>
	<string name="error_server_unknown" modified="true">Что-то не так с сервером</string>
	<string name="action_feedback" modified="true">Отослать обратную связь</string>
	<string name="about_title" modified="true">О программе</string>
	<string name="action_website_newwebsite" modified="true">Доступны новые вебсайты</string>
	<string name="not_implemented" modified="true">Не реализовано</string>
	<string-array name="pref_textsize_title"><item index="3">крупных</item><item index="4">сверхбольшой</item><item index="1">маленький</item><item index="2">средних</item><item index="0">чрезмерно малых</item></string-array>
	<string name="about_made" modified="true">Сделано с любовью</string>
	<string name="anecdote_share_title" modified="true">Поделиться через</string>
	<string name="action_share" modified="true">Поделиться</string>
	<string name="action_restore_summary" modified="true">Удалить все вебсайты из приложения. М.б. полезно для нерабочих.</string>
	<string name="open_intent_browser" modified="true">Открытие браузера...</string>
	<string name="dialog_website_error_itemperpage" modified="true">Пункт на страницу д.б. больше 0</string>
	<string name="dialog_website_error_selector" modified="true">Отсутствует выделение текста</string>
	<string name="dialog_website_page_name_hint" modified="true">Имя страницы</string>
	<string name="action_default" modified="true">Умолчание</string>
	<string name="action_retry" modified="true">Повтор</string>
	<string name="word_by" modified="true">с</string>
	<string name="app_migration_1_0_0" modified="true">Миграция на новую версию Anecdote</string>
	<string name="pref_rowstriping_title" modified="true">Полосатость строк</string>
	<string name="action_website_add" modified="true">Добавить вебсайт</string>
	<string name="action_settings" modified="true">Настройки</string>
	<string name="dialog_website_itemperpage_hint" modified="true">Количество элементов на странице</string>
	<string name="app_short_description" modified="true">Новые цитаты (9GAG, FML, Bash.org, xkcd) каждый день в простом приложении.</string>
	<string name="error_processing" modified="true">Что-то не так, пробуйте другие настройки вебсайта</string>
	<string name="pref_textsize_title" modified="true">Размер текста</string>
	<string name="action_about" modified="true">О программе</string>
	<string name="about_contentbelonging" modified="true">Содержимое приложения не принадлежит Anecdote.</string>
	<string name="dialog_website_error_name" modified="true">Добавить имя?</string>
	<string name="about_made_community" modified="true">С помощью сообщества https://github.com/HugoGresse/Anecdote</string>
	<string name="dialog_website_new_title" modified="true">Новый вебсайт</string>
	<string name="error_general" modified="true">Неизвестная ошибка...</string>
	<string name="action_open_inbrowser" modified="true">Открыть в браузере</string>
	<string name="action_delete" modified="true">Удалить</string>
	<string name="dialog_website_urlsuffix_hint" modified="true">(опц.) Суффикс номера страницы</string>
	<string name="pref_cat_display" modified="true">Отображение</string>
</resources>

**Comment by HugoGresse** [comment]
you can maybe esacape the whole string using the ` ``` ` character before and after it

**Comment by ashed** [comment]
Thanks. I attached zipped version of strings.xml in previous issue
