### ISSUE TITLE
NSF not working anymore

### ISSUE THREAD

**Issue by KabbAmine** [HugoGresse/Anecdote#62]
First of all thanks for your great app.

Unfortunately, the app do not load Nuit Sans Folie anymore (error 406), et c'est vraiment dommage :(.

**Comment by HugoGresse** [comment]
it seems to work again, can you confirm?

**Comment by KabbAmine** [comment]
Ok, looks like the version I was using is outdated (v1.1.5 from f-droid) and I've just tested the v1.2.2 from play market which is working as expected, NSF included.

Do you have any idea why f-droid build is so old?

**Comment by HugoGresse** [comment]
I've never tagged the 1.2.2 here and the PR is still open, I need to fix some Code Review issue. I'll try to do it soon.

**Comment by KabbAmine** [comment]
Ok, I'll wait then.

The issue can be closed, thanks again.
