### ISSUE TITLE
Can't zoom in pictures

### ISSUE THREAD

**Issue by remi13131** [HugoGresse/Anecdote#63]
It would be nice to be able to zoom on a picture when opened in full-screen. At the moment the picture take all possible space but sometimes it is quite hard to read a CommitStrip for example.

**Comment by HugoGresse** [comment]
I though the zoom is already into the release app; weird. Did you tried to pinch it with two fingers?

**Comment by remi13131** [comment]
Hmm this must have been released in the last update right ?      
It was not working up to very little time ago, but i just tried again at the moment and it works. 

Sorry not to have checked again before posting this issue. I close this.

**Comment by HugoGresse** [comment]
maybe a bug in the app, let me know if it happen again. 
Thanks for the issue though.
