### ISSUE TITLE
gradient grey overlay bottom button zone when zooming in images

### ISSUE THREAD

**Issue by remi13131** [HugoGresse/Anecdote#64]
Using the up-to-date fdroid version of anecdote, i can zoom in pictures (CommitStrip,...)

However, when doing this, the image comes full screen but an overlay of gradient gray subsides with sharing components at the bottom.

I'll update and post a screenshot, better than a thousand words, when i get back to a computer.

**Comment by HugoGresse** [comment]
Great, thanks. Can you also share your device model / versions?

**Comment by remi13131** [comment]
![whatsapp image 2018-04-26 at 17 46 03](https://user-images.githubusercontent.com/11832241/39316581-c949d47a-4979-11e8-8ec3-156264a40a3d.jpeg)

![whatsapp image 2018-04-26 at 17 43 58](https://user-images.githubusercontent.com/11832241/39316492-93d64012-4979-11e8-8d09-6042fba2464d.jpeg)

**Comment by HugoGresse** [comment]
I think you can single touch in the middle and the overlay will disappear.

**Comment by remi13131** [comment]
wow sorry for screenshots, they scale so big in the comments :o 

As you can see, i'm using some chinese crap, not a very common phone but the bug seems to reside in the app looking at the screenshot.

**Comment by remi13131** [comment]
Omg i'm sorry i'm so dumb... 
I indeed can single touch and overlay disappear...

Edit : I hate new version of android phones with virtual button instead of physical ones. That make the ui so much less intuitive :-(

Thank you for your time & reactiveness !
