### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [HugoGresse/Anecdote#65]
Hi, I want to design a new logo for the project completely free...

**Comment by HugoGresse** [comment]
Hi Arslanshn,

Feel free to submit your proposal!

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1BfxwZH-jZA5UAMebY3IuYwk9RLH942GY?usp=sharing
Hi I made the logo design.I hope you like it...

**Comment by HugoGresse** [comment]
hi Arslanshn,

Thanks for the logo but it is not very convincing comparing to the actual, a little old school.

**Comment by Arslanshn** [comment]
It can be logotype . If you interested we can talk about design choices. I am waiting your feedback!
Do you have any suggestions..
