### ISSUE TITLE
Confused about DOM selector

### ISSUE THREAD

**Issue by ahmadraniri1994** [HugoGresse/Anecdote#71]
I don't know if my question is fit here, I feel confuse when I face "DOM selector" on site setting, I want to open 9gag with this app but I can't figure it how.
Any advice? I am sorry if this is kinda embarrassing to ask silly question. Thanks.

**Comment by HugoGresse** [comment]
Thanks for your interest, unfortunately, 9GAG was present until they switch to a single page app, in javascript which make getting the data with only dom selector not possible. 
So for the moment I don't have a solution for 9GAG and I don't have enough time to work on it right now :/
