### ISSUE TITLE
Changing one selector in the api 

### ISSUE THREAD

**Issue by siefgred** [HugoGresse/Anecdote#73]
Hello 

I found an issue with the selector used for VDM  in https://anecdote-api.firebaseio.com/v2/websites.json 

The current selector is `#main article .block` and should be something like `#main w-full article .block`

By adding the "w-full", it permits to not take in account the 4 VDM that are on the left side of each page and avoid having these 4 VDM repeted every time a new page is crawled.

**Comment by HugoGresse** [comment]
Done! thanks for the update!

**Comment by siefgred** [comment]
Sorry @HugoGresse  , I made a mistake : `#main .w-full article .block` should be added instead of `#main w-full article .block`

**Comment by HugoGresse** [comment]
no worry, I've updated the conf! Thanks for the quick report and for getting me the solution!

**Comment by siefgred** [comment]
Arf, it is not working. 

After further investigation, I've found the final solution (and tested it by the custom site feature in the app) 
Because there are 2 elements levels with the ".w-full", need to add `#main .w-full .w-full article .block` instead.

Sorry for the 3 modifications in a row :/

**Comment by HugoGresse** [comment]
Done!

**Comment by siefgred** [comment]
It works! :)

**Comment by HugoGresse** [comment]
🎉

**Comment by HugoGresse** [comment]
if you want to have other source too, let me know and open a new issue
